### ISSUE TITLE
Cannot build with `human-panic` 1.0.2

### ISSUE THREAD

**Issue by dalcde** [rustwasm/wasm-pack#818]
Building is broken by `human-panic` 1.0.2 with error
```
error[E0063]: missing field `repository` in initializer of `human_panic::Metadata`
   --> /home/dexter/.cargo/registry/src/github.com-1ecc6299db9ec823/wasm-pack-0.9.1/src/main.rs:105:16
    |
105 |     let meta = human_panic::Metadata {
    |                ^^^^^^^^^^^^^^^^^^^^^ missing `repository`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0063`.
```
This is due to the commit https://github.com/rust-cli/human-panic/commit/a4b9d1c2f999ad93ef69cb383c0d7a5643201341

**Comment by mysterycommand** [comment]
I think I am also having this issue in CI, but it's building fine locally.

**Comment by dalcde** [comment]
I have this issue building locally. Have you run cargo update?

**Comment by mysterycommand** [comment]
@dalcde I have not, and now I think I won't! Cargo update would update transitive deps, which'd reresolve `human-panic` which'd get the 1.0.2 update that should've been a breaking change … it all makes sense to me, but also my CI setup is currently breaking on this, so having a the local ability to deploy is great. Don't even ask why I'm deploying on a Saturday night!

**Comment by b-m-f** [comment]
@mysterycommand I would recommend building from the `Cargo.lock` file on your CI.

**Comment by MartinKavik** [comment]
`human_panic` v. `1.0.2` has been yanked - https://crates.io/crates/human-panic and `1.0.3` has been released. So it should work again (according to our CI) without changes in PR https://github.com/rustwasm/wasm-pack/pull/819 (that PR is breaking it now, so it shouldn't be merged).

I think the main problem is that `cargo make install` doesn't respect dependency versions / `Cargo.lock`. When you write `cargo install wasm-pack --force --locked` it seems to respect it and install `human_panic` v `1.0.1`. This is probably a related issue - https://github.com/rust-lang/cargo/issues/7169.

Please correct me if I'm wrong.

P.S. I'm the maintainer of the [Seed](https://github.com/seed-rs/seed) framework and it broke our CI - there are some logs in GitHub Actions if anybody interested.
