### PR TITLE
Fix build with human-panic 1.0.2

### LINKED ISSUE #818: Cannot build with `human-panic` 1.0.2
Building is broken by `human-panic` 1.0.2 with error
```
error[E0063]: missing field `repository` in initializer of `human_panic::Metadata`
   --> /home/dexter/.cargo/registry/src/github.com-1ecc6299db9ec823/wasm-pack-0.9.1/src/main.rs:105:16
    |
105 |     let meta = human_panic::Metadata {
    |                ^^^^^^^^^^^^^^^^^^^^^ missing `repository`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0063`.
```
This is due to the commit https://github.com/rust-cli/human-panic/commit/a4b9d1c2f999ad93ef69cb383c0d7a5643201341

### PR DESCRIPTION
**Pull request by dalcde**
Fixes #818

### CODE REVIEW

**Comment by dalcde** [comment]
Closing since `human-panic 1.0.2` is yanked
