### ISSUE TITLE
hot reloading does not work anymore from version 0.10.2

### ISSUE THREAD

**Issue by QuentinJanuel** [rustwasm/wasm-pack#1123]
I have a  webpack project where I use wasm-pack to build one of my node dependencies.
It all worked fine on v0.10.1 but since v0.10.2 there is the following bug:
 - compile rust code
 - start the webpack devserver
 - recompile the rust code
At this point,
 - on v0.10.1, webpack simply reloadsthe page
 - on v0.10.2, webpack returns a "Module not found" compilation error

I have no idea what is causing this, and I just went back to using the ver0.10.1.

rustc version: 1.59.0

Please tell me if there is any detail I should include.

**Comment by PanAeon** [comment]
Related wasm-tool/wasm-pack-plugin#125
There's a working solution [in the thread ](https://github.com/wasm-tool/wasm-pack-plugin/issues/125#issuecomment-1004694898):
```
watchOptions: {
   aggregateTimeout: 200,
   poll: 200,
},
```
Adding this options to webpack.config.js resolves the issue for me.
