### ISSUE TITLE
wasm-pack 0.11.0 not work with yarn pnp

### ISSUE THREAD

**Issue by le0pard** [rustwasm/wasm-pack#1265]
## 🐛 Bug description

 - wasm-pack 0.11.0 not work with yarn pnp

#### 🤔 Expected Behavior

 - wasm-pack 0.11.0 to work with yarn pnp (like it doing 0.10.3 version)

#### 👟 Steps to reproduce

 - Install wasm-pack 0.11.0
 - Run `wasm-pack build`

Result:

```bash
node:internal/modules/cjs/loader:959
  throw err;
  ^

Error: Cannot find module '/Users/leo/programs/projects/browserlist/node_modules/wasm-pack/node ./run.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:956:15)
    at Module._load (node:internal/modules/cjs/loader:804:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

#### 🌍 Your environment

wasm-pack version: 0.11.0
rustc version: 1.65.0
yarn version: 3.2.2

**Comment by TimoWilhelm** [comment]
Seems like a duplicate of https://github.com/rustwasm/wasm-pack/issues/1248. There is an open PR (https://github.com/rustwasm/wasm-pack/pull/1250) to fix it, but that has stalled for close to 2 weeks 🤷‍♂️

Installing with NPM-like tooling is broken for `0.11.0`. So you can either patch the `package.json` bin path or downgrade to `0.10.3` until the PR gets merged.

**Comment by le0pard** [comment]
Yep, I am using 0.10.3 version right now

**Comment by haakonflatval-cognite** [comment]
I am also experiencing this, and it seems to be fixed by #1250 , which was merged three weeks ago. However, there hasn't been a new release. Could you release a 0.11.1, @drager ?

**Comment by haakonflatval-cognite** [comment]
Kind reminder that I'm still waiting for this, @drager

**Comment by haakonflatval-cognite** [comment]
@drager Could you please prioritize this?

**Comment by drager** [comment]
@haakonflatval-cognite @stefnotch Sorry for the delay. v0.11.1is now released:
* https://crates.io/crates/wasm-pack/0.11.1 
* https://www.npmjs.com/package/wasm-pack/v/0.11.1
